### ISSUE TITLE
Compile MF-NWT on debian jessie

### ISSUE THREAD

**Issue by rabbl** [modflowpy/pymake#6]
I'm trying to compile modflow-nwt on debian jessie, but I can't get it work.
I have tried with pymake, but thats not possible (like written in the documentation).

A makefile is not available with the source, so is there a known workaround?

**Comment by langevin-usgs** [comment]
@rabbl, there is some non-standard Fortran in MODFLOW-NWT at the moment.  You should be able to just fix those issues in the source code, which is what I had to do.  I don't remember the details, but I don't think they were difficult to fix.

**Comment by rabbl** [comment]
@langevin-usgs, sorry, but I'm not very familiar with fortran. 
Compiling on debian with pymake comes the following error-message:

```
gfortran -O2 -fbacktrace -ffpe-summary=overflow -c ./src_temp/gsol7.f -o ./obj_temp/gsol7.o -I./obj_temp -J./mod_temp
./src_temp/gsol7.f:326.25:

        USE, INTRINSIC :: IEEE_ARITHMETIC
                         1
Fatal Error: Can't find an intrinsic module named 'ieee_arithmetic' at (1)
Traceback (most recent call last):
  File "make_mfnwt.py", line 42, in <module>
    make_mfnwt()
  File "make_mfnwt.py", line 32, in make_mfnwt
    expedite=False, dryrun=False, double=False, debug=False)
  File "/usr/local/lib/python2.7/dist-packages/pymake/pymake.py", line 633, in main
    expedite, dryrun, double, debug, fflags)
  File "/usr/local/lib/python2.7/dist-packages/pymake/pymake.py", line 357, in compile_with_gnu
    subprocess.check_call(cmdlist, shell=shellflg)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gfortran', '-O2', '-fbacktrace', '-ffpe-summary=overflow', '-c', './src_temp/gsol7.f', '-o', './obj_temp/gsol7.o', '-I./obj_temp', '-J./mod_temp']' returned non-zero exit status 1
```

In the sourcecode on ./src_temp/gsol7.f:326.25 there is the following:

```
C-------CONJUGATE GRADIENT ITERATIVE SOLVER
      SUBROUTINE GSOL_CGAP(NCORESM,NCORESV,
     2                     IPC,ICNVG,ISOLN,NOUTER,NINNER,
     3                     HCLOSE,RCLOSE,ETA,NR,NNZ,DAMP,IA,JA,A,
     4                     NRLU,NNZLU,NJLU,NJW,NWLU,JLU,IU,JW,WLU,Mi,
     5                     X,B,X0,DSCALE1,DSCALE2,
     6                     D,P,Q,Z,T)
        USE, INTRINSIC :: IEEE_ARITHMETIC
        IMPLICIT NONE
```

What could I change to fix this?
Thanks for helping

**Comment by mjigmond** [comment]
**@rabbl** I'm not sure if it's an option for you, but IEEE_ARITHMETIC was added at GCC version 5 (https://gcc.gnu.org/gcc-5/changes.html). Even so, you'll run into a crash that I fixed by changing a data type in **gwf2swr7_NWT.f** (that itself will generate some warnings but make will succeed).

14351:        DOUBLEPRECISION, INTENT(INOUT) :: T1
change to
14351:        REAL, INTENT(INOUT) :: T1

because https://gcc.gnu.org/onlinedocs/gfortran/SECNDS.html.

**Comment by rabbl** [comment]
Thanks @mjigmond for your suggestions. Debian brings gcc 4.9 with it and I had some problems installing the 5.0 version.
I have solved the issue with compiling and using modflow-owhm for my use case and its compiling and running as expected.

**Comment by jdhughes-usgs** [comment]
The latest release of MODFLOW-NWT (v 1.1.1) available on the web includes changes so that it will compile with gfortran. I have updated the make_mfnwt.py script in the examples directory. I have also added functionality to create a makefile (-mf or --makefile option) with pymake. It works for gfortran on windows or mac (and presumably linux) and for ifort on mac (and presumably linux). It may be a little fragile but I will be doing more testing to clean up some deficiencies.

**Comment by langevin-usgs** [comment]
The make_mfnwt.py script seems to be working now (at least on my mac), due to the use of all standard Fortran in the latest NWT release.  Readme.md has been updated to reflect this.

Still need to add a NWT build to the autotesting, but that is a separate issue.
